(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
var h=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var d=0;d<a.length;d++)if(d in a&&a[d]===b)return d;return-1};function k(a){a=a===void 0?document:a;return a.createElement("img")};function l(a,b,d){typeof a.addEventListener==="function"&&a.addEventListener(b,d,!1)};function m(a,b,d){var c=!1;c=c===void 0?!1:c;a.google_image_requests||(a.google_image_requests=[]);var e=k(a.document);if(d){var f=function(){if(d){var g=a.google_image_requests,v=h(g,e);v>=0&&Array.prototype.splice.call(g,v,1)}typeof e.removeEventListener==="function"&&e.removeEventListener("load",f,!1);typeof e.removeEventListener==="function"&&e.removeEventListener("error",f,!1)};l(e,"load",f);l(e,"error",f)}c&&(e.attributionSrc="");e.src=b;a.google_image_requests.push(e)};function n(){var a=document.currentScript;return(a=a===void 0?null:a)&&a.getAttribute("data-jc")==="22"?a:document.querySelector('[data-jc="22"]')};var p=document,q=window;function r(a,b,d){if(Array.isArray(b))for(var c=0;c<b.length;c++)r(a,String(b[c]),d);else b!=null&&d.push(a+(b===""?"":"="+encodeURIComponent(String(b))))};function t(){var a=u["gws-id"],b=u["qem-id"];this.l=u.url;this.m=a;this.o=b;this.i=!1;a=w(p.hidden)?{g:"hidden",h:"visibilitychange"}:w(p.mozHidden)?{g:"mozHidden",h:"mozvisibilitychange"}:w(p.msHidden)?{g:"msHidden",h:"msvisibilitychange"}:w(p.webkitHidden)?{g:"webkitHidden",h:"webkitvisibilitychange"}:{g:"hidden",h:"visibilitychange"};this.g=a.g;this.h=a.h;this.j=-1;p[this.g]&&x(this,2);y(this);z(this)} 
function y(a){l(p,a.h,function(){if(p[a.g])a.i&&(a.i=!1,a.j=Date.now(),x(a,0));else{if(a.j!==-1){var b=Date.now()-a.j;b>0&&(a.j=-1,x(a,1,b))}x(a,3)}})}function z(a){l(q,"click",function(b){a.handleClick(b)})}t.prototype.handleClick=function(){var a=this;this.i=!0;q.setTimeout(function(){a.i=!1},5E3)}; 
function x(a,b,d){d=d===void 0?0:d;var c={gqid:a.m,qqid:a.o};b===0&&(c["return"]=0);b===1&&(c["return"]=1,c.timeDelta=d);b===2&&(c.bgload=1);b===3&&(c.fg=1);b=[];for(var e in c)r(e,c[e],b);m(q,a.l+"&label=window_focus&"+b.join("&"),!1);var f=f===void 0?.01:f;if(!(Math.random()>f)){a=n();a="https://"+(a&&a.getAttribute("data-jc-rcd")==="true"?"pagead2.googlesyndication-cn.com":"pagead2.googlesyndication.com")+"/pagead/gen_204?id=jca&jc=22&version=";c=(c=n())&&c.getAttribute("data-jc-version")||"unknown"; 
f=a+c+"&sample="+f;a=window;var g=g===void 0?!1:g;if(c=a.navigator)c=a.navigator.userAgent,c=/Chrome/.test(c)&&!/Edge/.test(c)?!0:!1;c&&typeof a.navigator.sendBeacon==="function"?a.navigator.sendBeacon(f):m(a,f,g===void 0?!1:g)}}function w(a){return typeof a!=="undefined"};var A=n();if(A==null)throw Error("JSC not found 22");for(var u={},B=A.attributes,C=B.length-1;C>=0;C--){var D=B[C].name;D.indexOf("data-jcp-")===0&&(u[D.substring(9)]=B[C].value)}window.window_focus_for_click=new t;}).call(this);
